export const names = [
  "21–87",
  "216 Signs",
  "31% Wool",
  "400",
  "A–Side.",
  "Aalia Ahamed",
  "Abbie Williams",
  "abc",
  "ACRE – A Creative Endeavour Ltd",
  "Active Matter",
  "ACX",
  "Adele Kelly",
  "AdesignStorie",
  "Advocate Design Agency",
  "Aetha Design",
  "Aileron Design Ltd",
  "Alan Pitchforth",
  "Alex Kimber Design",
  "Alexander Miller",
  "Alexandra Lunn Studio",
  "Alexandra Lunn Studio",
  "Alexie Sommer",
  "Alexis Bardini",
  "Ali Adair",
  "Andrew Carr",
  "ANdy Parker",
  "Andy Thornton",
  "Anja Klüver",
  "Annabelle Vuille",
  "Apfel",
  "Applied Works",
  "Archetype Accessories",
  "Arif Yusop",
  "Arrival",
  "Avery & Brown",
  "Badfish Labs",
  "Baines Design LTD",
  "Barbara Chandler",
  "Barbara Chandler",
  "Barry Bloye",
  "Batch.Works",
  "Baxter & Bailey",
  "Be The Future",
  "Beco",
  "Beehive Green",
  "Ben Clarke",
  "Ben Jessop",
  "Bencium Limited",
  "Benedict Povey",
  "Beta Design Office",
  "BIB Design",
  "big fish",
  "Big Motive",
  "Bill Searle",
  "Biomimicry Innovation Lab",
  "Bliss",
  "Blunt Crayon",
  "Bold Studio",
  "Boyle & Perks",
  "Brand Narrative at Pentagram",
  "Bravand",
  "Breezign",
  "Bright Signals Design at Bright Signals Ltd.",
  "Broadley Creative Ltd",
  "Bronwen Rees",
  "Buff Motion",
  "Butterfly",
  "BuyDesign",
  "Carter Studio",
  "Célibataire",
  "Charli Blighton",
  "Charli Peake",
  "Charlotte Eagle",
  "Charlotte Evans",
  "Cherry Anderson Freelance Design",
  "Chloe Poulter",
  "Claire O'Neill",
  "Claire Potter Design",
  "Clara Greo",
  "Clare Lewis",
  "Claudiu",
  "Clever Ghost",
  "Climate Labs",
  "Clive Russell",
  "COHDA Design",
  "Companion Studio",
  "Conscious Hospitality Ltd",
  "Conscious Sourcing",
  "Contour",
  "Creative at Delarki",
  "Creative Concern",
  "creative conscience",
  "Creative Joy",
  "Creative Joy",
  "Creative Wilderness LTD",
  "Curious Agency",
  "Curious Agency",
  "Curious Brand",
  "CyDen Ltd",
  "D Squared Product Development Ltd",
  "Daedalus",
  "Daryl Wilkinson",
  "Dave Cartledge",
  "Dave Cuvelot",
  "David Fairbrother",
  "David Sudlow Designers",
  "DEFY Brands",
  "Design Activists for Regenerative Futures",
  "Design Burger",
  "Design by Country Ltd",
  "Design by Mondial",
  "Design Council",
  "Design For Good Club",
  "Design for Joy",
  "Design Nature CIC",
  "Design Science",
  "Design Truth",
  "DesignWright",
  "DH Design Studios Ltd",
  "Dids Macdonald",
  "Dionne Griffith",
  "DISOMT",
  "Dominik Bini",
  "Dr Emma Powell",
  "Dr Karl Jeffries",
  "Drew Kendrick",
  "Driftime® Media",
  "Dylan Wiener",
  "ecologicstudio",
  "Edmuuund",
  "Electro Strategy",
  "Element Studio",
  "Eleven",
  "elise",
  "Ella Porter",
  "Elle Nelson Design",
  "Ellie Burroughs",
  "Emily Gorham",
  "EMMA BRITTAIN",
  "Emma Summerscales",
  "emmabakerstudio",
  "Eniola Ogunsola",
  "Ensemble",
  "Enviral",
  "Etch",
  "Ettive Design",
  "Europa",
  "Eva Koehle",
  "Everything",
  "Everywhere Design",
  "Exeter Waste",
  "F VENZANO",
  "Fairground Studio",
  "Farrah & Pearce Ltd",
  "FearNaught",
  "Fernanda Rizzo",
  "Ferrgood Studio",
  "Few and Far",
  "Fighting Talk Communications",
  "Fiona Watkins Design Limited",
  "Fixperts at Forth",
  "Foundation",
  "Founded Design Ltd",
  "Fourfeet Design",
  "Francesca Cook Design Ltd",
  "Francis Rowland",
  "Frankie Thelwell",
  "FranklinTill",
  "Future Selves",
  "Futurice Ltd",
  "Fynn",
  "G R Moore Limited",
  "G3 Creative",
  "Gareth Neal Ltd",
  "Gareth Wild",
  "Garlic Agency",
  "Genevieve Bennett Ltd",
  "Genuinely Conscious",
  "George Charnley",
  "George Rowland",
  "GET LOST",
  "Gianfranco Fagotto",
  "Gitta Gschwendtner Ltd",
  "Giulia Villa",
  "Glen Cutwerk",
  "Glimpse",
  "Good Design Works",
  "Good Stuff Creative",
  "Good Will Studios",
  "Goodtale",
  "Goodwin Hartshorn",
  "Graduate Studies at College for Creative Studies",
  "Graft Creative",
  "Green Mat Workshop",
  "Green Orbit Digital",
  "Green Rooms landscapes & gardens",
  "GreenHeights",
  "H&A",
  "Hamish Duncan",
  "Hamish Makgill",
  "Han Li",
  "Hannah Pinnock",
  "Harriet Beesley",
  "Harrison Brands Ltd",
  "Haughton Design",
  "Helen Simmons",
  "Hey Low",
  "Hippo Digital",
  "Hive IT",
  "Hiyield",
  "Holmes Studio",
  "honours",
  "HOUSE OF HACKNEY",
  "Hundred Studio",
  "ICE",
  "ilka design limited",
  "Imagination Factory",
  "Inspirwood",
  "INTRA DRIVE LTD",
  "Irina Teti",
  "Isabella",
  "Jackie Malcolm",
  "Jake Owen",
  "James Kindred",
  "James Tooze",
  "Jamie Pinkham",
  "jan lewis creative",
  "Jane Penty",
  "Jason Bruges Studio",
  "Jason Mesut",
  "Jemima Duncalf",
  "Jess Baxter",
  "Jess Francis",
  "JK Creative Company",
  "Jo Mansfield",
  "Joanna boehnert",
  "John Gilbert",
  "Joseph Folkes",
  "Josh Elgood",
  "Joshua Tunstill",
  "Jude Pullen",
  "Juice by Design",
  "Justine Wyness",
  "Kaelum van der Berg",
  "Kai Davis",
  "Kaleido Grafik",
  "Kaleido Grafik",
  "Kanika Kalra",
  "Karishma Kusurkar",
  "Kathryn Summers",
  "Kavya Narayanan",
  "Kenny Heard",
  "Kenwood Design Office (KDO) at Kenwood Limited",
  "Kim Trow",
  "Kinneir Dufort",
  "Kirsten Gord",
  "KLUVERWORKS",
  "Kyle Soo",
  "Kyle Stuart Florent Taylor",
  "Laura Santamaria",
  "Laure Rees-Smith",
  "Lawrence Zeegen",
  "Layerd.Studio",
  "Leap Design",
  "Lewis Plummer",
  "Liam O'Brien",
  "Lil Creative Studio",
  "Limber Brands",
  "Liquid Studio Ltd",
  "Lobo Creative",
  "LowCarbon",
  "Lucy Carruthers",
  "Lucy Watkins",
  "Luigi Gisolfi",
  "Lyon & Lyon",
  "MA Sustainable Design at University of Brighton",
  "Made for the World",
  "madeby.studio",
  "Magnus Long Studio",
  "Mainlyphotography Studio",
  "Mani I",
  "Mantra",
  "Mar Mar Co. Studio",
  "March Studio Ltd",
  "Maria Elina",
  "Marion Ratie",
  "Mark Hicks",
  "Marta De Prisco",
  "MARTA ROSSATO INTERIORS",
  "Martin Hopkins",
  "Martin Price",
  "Martin Wright",
  "Mat Denney",
  "Materialise Interiors",
  "Materials Council",
  "MaterialsInformation Ltd",
  "Matt Hollands",
  "Matteo Menapace",
  "Matter + Perspective",
  "Matthew Kilcullen",
  "Max Fraser",
  "Maya Designer",
  "Mia Allers",
  "Micha Nicheva",
  "Michael James",
  "Michael Love Design",
  "Michael Norrington",
  "Michael Rawling",
  "Midnight",
  "Minna Takala",
  "Mireia Allende",
  "Mitre and Mondays",
  "Mocean",
  "ModularPlastik",
  "Monica Oliveira",
  "MONOMOTIF",
  "Morrama",
  "Muddy Machines",
  "Muta Futures Studio",
  "Nagonic Design Ltd",
  "Naked Ideas",
  "Nat Hunter",
  "Natalia Benusiglio Stern",
  "Natalie Perkins",
  "Nefeli Pavlou Musio",
  "Neol.co",
  "Never Not Ready",
  "Nicola Holden Designs",
  "Nils Aksnes",
  "noel douglas",
  "Norah Joshi (Lewis)",
  "Noughts & Ones",
  "NU Creative Ltd",
  "NU Design Spaces",
  "Nurture",
  "Objective Studio",
  "observerly",
  "Octo Design Ltd",
  "OGRE Studio",
  "Ohana Studio Ltd",
  "Ok deploy",
  "Ole Makkesen  Designlab",
  "Olive Kennington",
  "Oliver Lloyd",
  "Olivia Harris",
  "OneKind Creative",
  "Optimist Works",
  "Oracle Design",
  "Orangery",
  "ORCA",
  "Osch",
  "Other Today",
  "OURI Labs",
  "OXygen",
  "Papaya–Studio",
  "Papillon Bleu",
  "Paul Bailey",
  "Paul Gibson Design",
  "Pearson Lloyd",
  "People Planet Product",
  "Phase Two",
  "Pixel Fridge LTD",
  "Pollenize CIC",
  "Polytechnic",
  "Poonum Chauhan",
  "Pretty Clever",
  "Product Design at University of Brighton",
  "Product Design at University of Sussex",
  "Product for Net Zero",
  "Purple Banana",
  "QED web design",
  "Rahul Anand",
  "Realise",
  "Rebekah Di Palma",
  "ReShaped Landscape",
  "Rhapsody Media",
  "Rhombus Studio",
  "Ria Hawthorn",
  "Richa Gandhi",
  "Robin Wong",
  "Roddy Clarke",
  "Rory Cowan",
  "Roundwave",
  "Ruddocks",
  "Ruth Wassermann Ltd",
  "Sabotage",
  "Sam Judge",
  "Samuel Marchant",
  "Sandrine Herbert-Razafinjato",
  "sassd",
  "School of Good Services",
  "Selesti",
  "Selina Rose",
  "Set Studio",
  "Seth Campbell",
  "Simone Cucchi",
  "Snook",
  "Social Change",
  "Sophie Mockridge",
  "Sophie Reynolds",
  "Sophie Thomas",
  "Spark & Bell",
  "Special Projects",
  "Spotless",
  "Sruti Gidugu",
  "Standfirst",
  "Stefan Bassing",
  "Still&Nimble",
  "Storo",
  "Straight Forward Design",
  "Stuart Gough",
  "Studio Breuil",
  "Studio Casey Joy",
  "Studio Elk",
  "Studio Elma",
  "Studio Every",
  "Studio Gallant",
  "Studio Joana",
  "Studio KICO",
  "Studio Mothership",
  "Studio Olivers",
  "Studio Ology",
  "Studio Output",
  "Studio Overberg",
  "Studio Simple",
  "Studio Technical Nature",
  "Studio Tom Metcalfe",
  "Studio Wood",
  "Submarine",
  "Substance",
  "Superfried",
  "Susanna Edwards",
  "Susannah Kabuiku",
  "Sustainable Ventures Design",
  "T&B Design",
  "Tacit-Tacit",
  "Takram",
  "TAMART",
  "Tempest",
  "TEN by Anatomy HCD Limited",
  "Teresa Ferreira Studio",
  "Terrarium",
  "The Art and Design Consultancy",
  "The Blooming Platypus",
  "The Creative Bloc",
  "The Digital Creative London Ltd.",
  "The Discourse",
  "THE FOURTH SOLUTION",
  "The Landscape",
  "The Looking Glass",
  "The Manufacturing Technology Centre",
  "Theo Dormer",
  "Think/Do",
  "Thinkpublic",
  "Thom Baker Consultancy",
  "Thomas Baraldi Cassaro",
  "Thomas Wylam",
  "thomas.matthews",
  "Thoughtcraft",
  "Tijana Tasich",
  "Tim Frenneaux & Co",
  "Tina Bernstein",
  "TLC",
  "Tokyo Calm",
  "Tokyo Calm",
  "Tom Greenwood",
  "Tomas Gecim",
  "Tommy Papaioannou",
  "Tria Design",
  "Tristan Palmer Studio",
  "Two",
  "Two Degrees Studio",
  "Tŷ Syml",
  "Unboxed",
  "Unfound Studio",
  "United by Design",
  "UnlikelyGenius",
  "URGE Collective",
  "Vashti Waite",
  "Vestre Ltd",
  "Vicky Lofthouse",
  "Virgile Janssen",
  "Visual Print and Design",
  "VIVID NINE",
  "Vovi",
  "Vox Aeris",
  "Vu Online",
  "We Are Service Works Ltd",
  "We Are Systematic",
  "We Made This Ltd",
  "We Mean This",
  "WEAMO",
  "West9 Design",
  "White Weft Limited",
  "Wholegrain Digital",
  "WizzDev",
  "Working with Joe Ltd",
  "Works in Public Ltd",
  "www.archetypeaccessories.com",
  "xforwhy",
  "XTATX Studio",
  "Yarn Creative",
  "yesim tuzun",
  "Yoke design",
  "Zebra Growth Limited",
  "Zoe Bather",
  "ZOOZLY"
];


export const countries = [
  {
    country: 'Argentina',
    names: ['Celina Hilbert']
  },
  {
    country: 'Australia',
    names: [
      'Alena Smith Interior Design',
      'Andrew Sloan',
      'Andrew Vaughan',
      'Andy Marks',
      'Arielle Breit',
      'Art Disrupt',
      'Austin Smidt',
      'AUTHENTIC DESIGN ALLIANCE (ADA)',
      'Ben Rennie',
      'BETTER FUTURE',
      'Bohdan Dorniak & Co Pty Ltd - PROSPECT, SA',
      'Brand & Communications at Edge Impact',
      'Breathe Architecture',
      'BWD Strategic',
      'Cameron Tonkinwise',
      'Carbon Creative',
      'Carolyn King',
      'Celine Waters',
      'Charlotte Adams',
      'Design by Nature',
      'Design Consigned',
      'Diadem',
      'Dr Michelle Douglas FRSA',
      'eco creative agency',
      'Ethos Digital Agency',
      'Finbar',
      'Founded by Design Pty Ltd',
      'Frost*',
      'Frost*',
      'Gabriella Wilson',
      'Genius Agency',
      'Geoff Isaac',
      'Glen Barry',
      'Glen Barry',
      'Gloria Quiroga',
      'Good 4 Business',
      'Good Design Australia',
      'Good Design Australia',
      'Goodness',
      'Goodsports',
      'Hammond Studio',
      'Harry Steer',
      'Heidi Romano',
      'Holonic',
      'Hortenzia',
      'James Hodgson Design',
      'Jas Soh',
      'Jeremy Yuille',
      'Jo Li Tay',
      'John Young',
      'Josh Riesel',
      'Karina Clarke',
      'Katapult Design',
      'Kirby C',
      'Koskela',
      'Leigh Phillips-Brown',
      'Leigh-Anne Hepburn',
      'Leyla Acaroglu',
      'Liane Rossler',
      'LPB Designs and Interiors',
      'Madeline Johnston',
      'Make Tomorrow™',
      'Marnie Hawson',
      'Martin Tomitsch',
      'MEK Studio',
      'Mirella Arapian',
      'Moffitt.Moffitt.',
      'Motherbird',
      'Nacara Studio',
      'Nila Rezaei',
      'Particle Design Studio',
      'Philip Ely PhD',
      'philo & co',
      'Planitree',
      'Reny Studio',
      'Reny®',
      'Ricardo Sosa',
      'RK Collective',
      'RMIT University',
      'Samuel Yu',
      'Seek & Design',
      'Snug House',
      'Society for Responsible Design Inc.',
      'Sponge',
      'Stephanie Mulder',
      'Steve Baty',
      'STUDIO PERISCOPE',
      'Studio Regina',
      'studiospillane',
      'Tanisha Maria Naik',
      'The Design Thinkers',
      'UNEND',
      'United Studio',
      'vert design',
      'Wendy Fountain',
      'X+O',
      'Ys',
      'Zero Co pty Ltd'
    ]
  },
  {
    country: 'Austria',
    names: ['Luain']
  },
  {
    country: 'Bangladesh',
    names: ['Rifat Anik']
  },
  {
    country: 'Belgium',
    names: [
      'Air',
      'Blue Kameleon SRL',
      'Core Branding',
      'Futurewave',
      'HIER',
      'Orb'
    ]
  },
  {
    country: 'Brazil',
    names: [
      'Adriana Tamashiro',
      'Agatha Martins',
      'Alexander Ângelo Guazzelli',
      'Alexandre de Oliveira Lot',
      'Amanda Lima Neves Scorsolini',
      'Ana Luísa Canto',
      'Ana Paula Batista',
      'Audrey Italo Melo',
      'BRQ Digital Solutions',
      'Bruna Cerasi',
      'Bruna Luiza Schwendler',
      'Bruna Mattos',
      'Brunna Moura',
      'BRUNO FREIRE PERRONE',
      'Cacto Publicidade',
      'Camila Calegari Marques',
      'Camila de Almeida Santos',
      'Camila Lozeckyi',
      'Carlos Filipe Alves Lima',
      'Carlos Ignacio Hernández Tellez',
      'Carol Hoffmann',
      'CECILIA PACHECO',
      'Chelles & Hayashi Design',
      'christian ullmann',
      'Claudia Mardegan',
      'Claudio Pelizari',
      'Danton Gravina',
      'Denilson Silva',
      'Denise Oliveira Martins',
      'Design Docol at Docol Sanitaryware',
      'Design Team at WIS Learn',
      'DI',
      'Diego Nunes',
      'Diogo Lucato',
      'DPO Saudável',
      'Echos',
      'Eduardo Maia',
      'Eliane Quadro',
      'Empathy Company',
      'Estúdio Atômico',
      'Estúdio Guto Requena',
      'Estudio Marte',
      'Fares Saba Jr',
      'Fernanda',
      'Fernanda Fidelis',
      'Fernanda Romera',
      'Fluyd',
      'Francisco Albuquerque',
      'GABRIEL ESTEVES DE OLIVEIRA LEITAO',
      'George Rutherford',
      'GIOVANA LORENA FAZIONI',
      'Green Mandarin',
      'Green Mandarin',
      'Greg Lopes',
      'IMK Arquitetura e Engenharia',
      'Jaakko Tammela',
      'Jenifer Rodrigues',
      'Juan Solís Gundín',
      'JULIA RESENDE',
      'Júlia Timponi',
      'JULIANA SIDSAMER',
      'Julianny aidel rafea',
      'Junior Magalhães',
      'KAREN TIE KAWAKAMI',
      'Karla Scherer',
      'Larissa Nunes',
      'Leo Eyer',
      'Leonardo Lins',
      'Lincoln Seragini',
      'Lincoln Shiguio',
      'Lincoln Shiguio',
      'Luciana Shirakawa',
      'LUIS FERNANDO OSCAR COSTA',
      'Maialu Ferlauto',
      'Marcelo F. Pereira Junior',
      'Marcelo Sales',
      'Marcon Zanin',
      'Marcos Vinícius Machado de Oliveira',
      'Maria de Fátima Gullino Frazão',
      'Maria Elisa Zaia',
      'Mariana Fonseca de Souza',
      'Mariana Pereira Weber',
      'Mateus Bull Furlan',
      'Mayra Sasso',
      'Nathalia Petta',
      'paaassos design studio',
      'Pamela Basilio',
      'Patricia Watson',
      'Paula Cristiani Takahashi',
      'Paulo Peres',
      'Paulo Santos',
      'Pedro Gomes',
      'Pedro Martins e Souza',
      'Pedro Naif',
      'Pedro Pazitto',
      'PPTzeiros',
      'Raissa Esther',
      'Raquel Lima',
      'RedBandana Branding and Design',
      'Rei Campos Inovação em Serviços',
      'Renan Benvenuti',
      'Renan Migliorini',
      'Renata matos',
      'Renato Winnig',
      'Robson Zumkeller',
      'Robson Zumkeller',
      'RODRIGO ANTONIO QUEIROZ COSTA',
      'Rodrigo Peixoto',
      'Sandra Ribeiro Cameira',
      'Simbïo Design',
      'Studio Allure',
      'tellus',
      'Thayane',
      'Thiago Barreto',
      'Thiago Vieira Marques',
      'Thoz',
      'tiago taveira',
      'Tudo é Acessibilidade',
      'UERJ',
      'Vagner Trevisan',
      'Vanessa Silva',
      'Victor Maluhy',
      'Victor Mascarenhas',
      'VIRGINIA CORNELSEN',
      'Visorama',
      'Wagner Lúcio',
      'weme'
    ]
  },
  {
    country: 'Bulgaria',
    names: ['Ivelina Dimitrova']
  },
  {
    country: 'Canada',
    names: [
      'Ardeshir Amini',
      'Cense Ltd.',
      'Eliane Bowden',
      'Fletcher Scott Studio Inc.',
      'Meghan Hellstern',
      'PiTCH PR',
      'PiTCH PR',
      'Project 42',
      'Ryan Mayer',
      'SUPERFORT Creative Agency'
    ]
  },
  {
    country: 'China',
    names: [
      'Campaign Design',
      'Orange Creatives',
      'Platform88'
    ]
  },
  {
    country: 'Colombia',
    names: [
      'Coombo',
      'Leticia'
    ]
  },
  {
    country: 'Croatia',
    names: [
      'Creek and Pine',
      'Protagonist agencija'
    ]
  },
  {
    country: 'Czechia',
    names: ['Sandra']
  },
  {
    country: 'Denmark',
    names: [
      'BineJoMo Studio',
      'CurledDesign',
      'Louise Ryberg',
      'Make Material ApS',
      'Sabin Bors',
      'TAWS'
    ]
  },
  {
    country: 'Finland',
    names: ['Diseño y diáspora podcast']
  },
  {
    country: 'France',
    names: [
      'Archipel Kyosei at Archipel Kyosei',
      'Atelier de recherche temporelle at a-r-t',
      'Campus des Métiers et des Qualifications Image et Design Hauts de France',
      'Christopher Bellamy',
      'CY school of design',
      'Kristen',
      'LAB\'S 214',
      'madd-bordeaux',
      'OUTERCRAFT',
      'Valérie Tortolero'
    ]
  },
  {
    country: 'Germany',
    names: [
      'Amarjith Sreekumar',
      'andreas popp',
      'Ashley Scarborough',
      'Bendcircular',
      'Bureau Braun',
      'Gloria Ciceri',
      'hoch E',
      'JDS',
      'Jessica Metro',
      'Joshua Stehr',
      'Katharina Winter',
      'Matt Granger',
      'NEW STANDARD.STUDIO',
      'Paolo de Jesus',
      'Philip Hugle',
      'Plan C. Studio',
      'Schober+Richter',
      'STUDIO CDW',
      'The Design & Emotion Lab',
      'Thorsten Jonas',
      'Tillmann Schrempf',
      'White Lime'
    ]
  },
  {
    country: 'Gibraltar',
    names: ['Entain']
  },
  {
    country: 'Guatemala',
    names: ['Fabrizio Constanza']
  },
  {
    country: 'India',
    names: [
      'A BLUNT STORY',
      'Aboa Hasa Foundation',
      'Dinu Prasanna Kennedy',
      'DxE Inc.',
      'LOCAL',
      'Minto Joy',
      'Sai Challa',
      'Shona Sinha',
      'Shreya Salian'
    ]
  },
  {
    country: 'Indonesia',
    names: [
      'Andini Putri Pramudya Wardani',
      'Nice To Meet You Studio',
      'Skemasocial'
    ]
  },
  {
    country: 'Ireland',
    names: [
      'A Worthy Cause',
      'Aaron O\'Neill',
      'Abigail Smith',
      'Alanna Campbell',
      'Alessandra Ravida',
      'Alkamee',
      'Alphabet Soup',
      'Anastasiia Chorna',
      'Andrew Anderson',
      'Babelfís',
      'BIEN',
      'Billion Studio',
      'Bradley: The Brand Agency',
      'Bren Byrne',
      'Brian Morgan',
      'Caio',
      'Cairenn',
      'Capulet and montague',
      'Carlos Garcia',
      'Chapter',
      'Chart Design Studio',
      'Ciara Broujos Design',
      'Ciara Layden',
      'Ciara Wade',
      'Circular Design Institute',
      'Claire Dillon',
      'Claire Dillon',
      'Clare Lynch',
      'Claudia Fini',
      'Claudine Curran',
      'Claudine Leonard Design',
      'Clever Ghost at Clever Ghost',
      'Cliodhna Ryan',
      'Conor Flood',
      'Conor Nolan',
      'consider it design',
      'Context Studio',
      'CREW',
      'Cróna Connolly',
      'CUBE Design',
      'Damian Sherlock',
      'Dan Eames',
      'Danielle Deveney',
      'Danielle Townsend',
      'David Wall',
      'Déanta Studio',
      'Declan Behan',
      'Design for Sustinability & Circular Economies Certificate at Limerick School of Art & Design , TUS',
      'Design Notions',
      'Design Partners',
      'Design Studio at Maverick Communications',
      'Detail Design Studio',
      'Digital Factory at ESB',
      'Disco Milk',
      'Duanna Taylor Rooney',
      'Each&Other',
      'Éilís Murphy',
      'Éimear O\'Sullivan',
      'Emberlight',
      'Emi Daly',
      'Emma Nolan',
      'EPIC Interpretive Design',
      'Fly Bird Design',
      'FUSE Graphic Design Ltd',
      'Global Creative at Johnson Controls',
      'Good As Gold',
      'Grace',
      'Graphic Design [+] at IADT',
      'Graphic Design Communication at LSAD at TUS',
      'Griffith College Design',
      'Image Now',
      'Image Now',
      'Imagine Lab',
      'Iman',
      'Ingrid Smyth',
      'Institute of Designers Ireland',
      'Isabel Staunton',
      'Jamie Whelan',
      'Jeffers & Sons',
      'Joan Ellison',
      'Johanna Legnar',
      'John Connolly',
      'John Connolly',
      'John O\'Brien',
      'Jonny Willis',
      'Kacper Jaroszynski',
      'Kalil Dunne',
      'Kanupriya Jamwal',
      'Karl Smyth',
      'Karl Toomey',
      'Kate Brangan',
      'Katy May O\'Sullivan',
      'Kelly Hood',
      'Lands',
      'Lara Hanlon',
      'Lisa Zimmermann',
      'Lucy Bowen',
      'Luke McLaughlin',
      'M-CO',
      'MAKER',
      'Mallory Frye',
      'Marguerite',
      'Marie Gordon',
      'Marino Software',
      'Meghan Clapham',
      'Melvin Jayson C. Ogbalu',
      'Michelle Urban',
      'Mike Mahon',
      'New Graphic',
      'Neworld',
      'Oisin MacManus',
      'Olivia humphreys',
      'On The Dot',
      'Open Studio',
      'Outburst Design',
      'Path',
      'Patrick Feeney',
      'Paula McEntee',
      'Penhouse Design',
      'Peter Sheehan Studio',
      'Piquant',
      'Pixelpod',
      'POND Studios',
      'Portion Collaborative',
      'Post Studio',
      'Prof Dip and MA Service Design team at National College of Art and Design',
      'Public Design Lab at IADT',
      'Purple Peach',
      'Raluca Turcanasu',
      'Rebecca Wright',
      'Rebecca Wright',
      'Red Dog',
      'Richard Whitty',
      'RIFORMA collective',
      'Róisín Jordan',
      'Ross Harrington',
      'Ruairí Crawley',
      'Sadhbh Murphy',
      'Sasha Sykes Studio',
      'Self employed - Nichola Wolfe.com',
      'Serena Chille',
      'Shane Casey',
      'Sharon Maxwell',
      'Signal Type Founddry',
      'SLMD',
      'So Studio',
      'Sorcha Fitzgerald',
      'Stefan Paz',
      'Studio Kosmos',
      'Studio Saol',
      'studiomir',
      'Superfolk',
      'Susan Carberry',
      'Sweet! Graphic Design',
      'The Factory',
      'The FACTORY',
      'The Public House',
      'THINKHOUSE',
      'Together We Create',
      'Treetop Studio',
      'University of Limerick',
      'Unthink',
      'Wes Trumble Design',
      'Wilson Creative',
      'Wove'
    ]
  },
  {
    country: 'Isle of Man',
    names: ['Studio Cooper']
  },
  {
    country: 'Italy',
    names: [
      'acy',
      'chiara de angelis',
      'Elisabeth Graf',
      'Gianluca Menini',
      'Kāvya Raman',
      'Michael Brenner',
      'Ox design studio',
      'Simona Audino'
    ]
  },
  {
    country: 'Japan',
    names: ['Asuka Kondo']
  },
  {
    country: 'Latvia',
    names: [
      'Drinking Water',
      'Ēvija Kraukle'
    ]
  },
  {
    country: 'Lebanon',
    names: ['Designerwork']
  },
  {
    country: 'Lithuania',
    names: ['Viktorija']
  },
  {
    country: 'Luxembourg',
    names: ['Art Square Lab SARL-S SIS']
  },
  {
    country: 'Malta',
    names: ['Abigail Farrugia']
  },
  {
    country: 'Mexico',
    names: [
      'Alex Quinto',
      'Gustavo González D\'Asseo',
      'HD*',
      'Monserrat Aranzazú Moreno García',
      'Narativ Design'
    ]
  },
  {
    country: 'Morocco',
    names: ['evergreen pixel agency']
  },
  {
    country: 'Netherlands',
    names: [
      'Archites',
      'Circu Leren',
      'Creative Mules',
      'Danni Swalef',
      'Edwin van Maanen',
      'Gabriela Bassa',
      'Leon van Hoof',
      'Nadine',
      'Rg/B',
      'Rogier Barendregt',
      'Rogier Barendregt',
      'Sustainable Digital Design',
      'Wessel Jansen'
    ]
  },
  {
    country: 'New Zealand',
    names: [
      'Andrew Roberts',
      'Clark Bardsley Design',
      'Dani Bond'
    ]
  },
  {
    country: 'Nicaragua',
    names: ['Bernardo van de Schepop']
  },
  {
    country: 'Nigeria',
    names: [
      'Nuel Wogundu',
      'Ridwan Awujoola'
    ]
  },
  {
    country: 'Norway',
    names: [
      'Petchy',
      'Respira'
    ]
  },
  {
    country: 'Pakistan',
    names: [
      'Ali Murtaza',
      'Syed Faizan Raza'
    ]
  },
  {
    country: 'Philippines',
    names: [
      'Darwin Antipolo',
      'Jesi Sumeg-ang',
      'Mathijs Sterrenburg',
      'TAYO Change Agency: House of Culture & Creativity'
    ]
  },
  {
    country: 'Poland',
    names: [
      'Ergodesign',
      'Weronika Wojnarowicz'
    ]
  },
  {
    country: 'Portugal',
    names: [
      'Afonso Miguel Tomaz Assis dos Santos Januário',
      'Bernd Herbert',
      'Carolina Borges Sacoto',
      'Crystal Campbell',
      'Daniela Veloso',
      'FERNANDO MENDES',
      'Graeme McCree',
      'Joana Casaca Lemos LDA',
      'Pedro Miguel Gago Pereira',
      'Rossouw Oosthuizen',
      'Tassiane Castro'
    ]
  },
  {
    country: 'Romania',
    names: [
      'Alex Ardelean',
      'Madalina Hamciuc'
    ]
  },
  {
    country: 'Singapore',
    names: [
      'Audrey Yang',
      'Dignité Brands'
    ]
  },
  {
    country: 'Slovenia',
    names: [
      'Petra Černe Oven',
      'Sito'
    ]
  },
  {
    country: 'South Africa',
    names: [
      'Duncan Stevens',
      'the earth is round'
    ]
  },
  {
    country: 'Spain',
    names: [
      'Alberto Carnero',
      'Banda',
      'Blackbot',
      'Catalina Estrada',
      'David O\'Mahony',
      'Design Thinkers Group Spain',
      'Diego González',
      'Edu Gonzalez',
      'Elena Martinez',
      'estudio flúor',
      'Estudio República',
      'Federico Víllora',
      'Folks',
      'Folks Brands',
      'Gerard',
      'Glenn Goodwin',
      'holon coop',
      'Jesús Gallent',
      'Laura Fernández',
      'Lucinda Morrissey',
      'María Jesús Bonafonte',
      'Mean Creative',
      'Monnou',
      'MOS. More on Simplicity',
      'MUAK STUDIO',
      'Nixae',
      'PATRICIA SALCEDO',
      'The Hatch Studio'
    ]
  },
  {
    country: 'Sweden',
    names: [
      'Antrop',
      'Simone De Vivo'
    ]
  },
  {
    country: 'Switzerland',
    names: [
      'Blitz & Donner',
      'Cerca Research & Design Lab',
      'Reform GmbH',
      'Sarah Santacroce',
      'she explores tech',
      'Swiss Design Association',
      'Valerie Notter de Rabanal'
    ]
  },
  {
    country: 'Thailand',
    names: ['Tipaponr Tharawongthawat']
  },
  {
    country: 'Turkey',
    names: [
      'Bilal Akpinar',
      'Gaye Poçan'
    ]
  },
  {
    country: 'United States',
    names: [
      '2911 Creative LLC d/b/a Missionspring Studio',
      '76West',
      'Amanda Bauer',
      'Analogy',
      'Angeline Neo',
      'Autumn Dahlia Creative Services LLC',
      'Box Clever',
      'Brayan',
      'Business4Today.com',
      'Chameleon Studios',
      'Colibrily LLC',
      'Damn Good Humans',
      'Dayani',
      'Design Team at Omura',
      'Double Loop Marketing LLC',
      'Douglas Flandro',
      'Elliott Swigert',
      'Fabricio Teixeira',
      'Gooey.AI',
      'GROUP OF HUMANS',
      'Indiblu Creative',
      'James Junk',
      'Kailyn Nelson',
      'Kinship Creative',
      'Kristin keilt',
      'Lucy Crelli',
      'Lwindesign',
      'M.S.Architecture - Health and Design at NYIT Health and Design',
      'Matterall',
      'Mayra Cardoso do Nascimento',
      'Michael Weschler Productions',
      'Mike Simpson Design',
      'Mother\'s Tongue',
      'Re-nourish',
      'Rkive Studio',
      'Sara Mckee',
      'shannon',
      'Social Workers Who Design',
      'SPACES',
      'Stefan Boublil',
      'STORM studio',
      'Studio SAKA',
      'Style & Entertaining',
      'Urna Bloom',
      'What if Design',
      'WHYWHATIF'
    ]
  },
  {
    country: 'Uruguay',
    names: [
      'Helen Hartley Consulting',
      'Lucia Delgado',
      'Upgrade'
    ]
  },
  {
    country: 'Vietnam',
    names: ['Dr Britta Boyer']
  }
];